name: tryCatch
description: "열정 하나로 성취하는 가장 확실한 방법"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  chip_radio_button: ^1.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/intro/
    - assets/process/
    - assets/review/


  fonts:
    - family: Arita
      fonts:
        - asset: assets/fonts/Arita/AritaDotumKR-Medium.ttf
        - asset: assets/fonts/Arita/AritaDotumKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arita/AritaDotumKR-Light.ttf
        - asset: assets/fonts/Arita/AritaDotumKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arita/AritaDotumKR-Thin.ttf
          weight: 200